CREATE DATABASE EJEMPLOMVC
GO
USE EJEMPLOMVC
GO
CREATE TABLE Categoria
(
	IDCATEGORIA INT NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(200)
	PRIMARY KEY(IDCATEGORIA)
)
GO
CREATE TABLE Producto
(
	IDPRODUCTO INT NOT NULL IDENTITY(1,1),
	DESCRIPCION VARCHAR(MAX) NOT NULL,
	PRECIO DECIMAL(16,4) NOT NULL,
	IMAGEN VARCHAR(MAX) NULL,
	IDCATEGORIA INT NOT NULL,
	PRIMARY KEY(IDPRODUCTO),
	FOREIGN KEY(IDCATEGORIA) REFERENCES Categoria
)
GO
INSERT INTO Categoria(NOMBRE) VALUES('HERRAMIENTAS'),('HOGAR'),('ELECTRONICA'),('BELLEZA'),('ESTUDIO');
GO
